apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: folder4study
  labels:
    app: zookeeper
    version: latest
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - name: port
      port: 2181
      targetPort: port